theme: jekyll-theme-minimal
title: Joseph Natanael Marshan
description: Website build for fun
email: joseph.marshan@anu.edu.au
twitter_username: JosephMarshan
github_username: jnmarshan
author: Joseph Marshan

#build settings
