theme: jekyll-theme-minimal
title: Joseph Natanael Marshan
description: Website build for fun
email: joseph.marshan@anu.edu.au

#author setting
author: Joseph Marshan
  twitter_username: JosephMarshan
  github_username: jnmarshan

#build settings
