theme: jekyll-theme-minimal
title: Joseph Marshan
description: I am a PhD student at Australian National University
email: joseph.marshan@anu.edu.au

#author settings
author: Joseph Marshan
  twitter_username: JosephMarshan
  github_username: jnmarshan

#build settings
