theme: jekyll-theme-minimal
title: Joseph Marshan
description: "PhD student at Research School of Economics, Australian National University"
email: joseph.marshan@anu.edu.au

#author settings
author: Joseph Marshan
